# Configuración del servidor
server.port=8082

# Nombre de la aplicación
spring.application.name=business-service

# Configuración de Feign
# URL base para el data-service
data-service.url=http://localhost:8081

# Configuración de logging
logging.level.com.example.businessservice=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.cloud.openfeign=DEBUG